/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Juego.Cromosoma;
import Juego.Genetica;
import javax.swing.ImageIcon;

/**
 *
 * @author cristobal
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        this.limpiarTablero();

    }
    
    public void visualizarTablero (Cromosoma individuo) {
    
        for (int i = 0; i < individuo.vec_solucion.length; i++) {
            colocarIcono(individuo.vec_solucion[i] , i);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn0_0 = new javax.swing.JButton();
        btn0_2 = new javax.swing.JButton();
        btn0_1 = new javax.swing.JButton();
        btn0_3 = new javax.swing.JButton();
        btn0_7 = new javax.swing.JButton();
        btn0_4 = new javax.swing.JButton();
        btn0_5 = new javax.swing.JButton();
        btn0_6 = new javax.swing.JButton();
        btn1_0 = new javax.swing.JButton();
        btn1_1 = new javax.swing.JButton();
        btn1_2 = new javax.swing.JButton();
        btn1_3 = new javax.swing.JButton();
        btn1_4 = new javax.swing.JButton();
        btn1_5 = new javax.swing.JButton();
        btn1_6 = new javax.swing.JButton();
        btn1_7 = new javax.swing.JButton();
        btn2_0 = new javax.swing.JButton();
        btn2_7 = new javax.swing.JButton();
        btn2_1 = new javax.swing.JButton();
        btn2_2 = new javax.swing.JButton();
        btn2_3 = new javax.swing.JButton();
        btn2_4 = new javax.swing.JButton();
        btn2_5 = new javax.swing.JButton();
        btn2_6 = new javax.swing.JButton();
        btn3_0 = new javax.swing.JButton();
        btn3_1 = new javax.swing.JButton();
        btn3_2 = new javax.swing.JButton();
        btn3_3 = new javax.swing.JButton();
        btn3_4 = new javax.swing.JButton();
        btn3_5 = new javax.swing.JButton();
        btn3_6 = new javax.swing.JButton();
        btn3_7 = new javax.swing.JButton();
        btn4_7 = new javax.swing.JButton();
        btn4_6 = new javax.swing.JButton();
        btn4_5 = new javax.swing.JButton();
        btn4_4 = new javax.swing.JButton();
        btn4_3 = new javax.swing.JButton();
        btn4_2 = new javax.swing.JButton();
        btn4_1 = new javax.swing.JButton();
        btn4_0 = new javax.swing.JButton();
        btn5_0 = new javax.swing.JButton();
        btn5_1 = new javax.swing.JButton();
        btn5_2 = new javax.swing.JButton();
        btn5_3 = new javax.swing.JButton();
        btn5_4 = new javax.swing.JButton();
        btn5_5 = new javax.swing.JButton();
        btn5_6 = new javax.swing.JButton();
        btn5_7 = new javax.swing.JButton();
        btn7_0 = new javax.swing.JButton();
        btn6_0 = new javax.swing.JButton();
        btn6_1 = new javax.swing.JButton();
        btn7_1 = new javax.swing.JButton();
        btn6_2 = new javax.swing.JButton();
        btn7_2 = new javax.swing.JButton();
        btn6_3 = new javax.swing.JButton();
        btn7_3 = new javax.swing.JButton();
        btn6_4 = new javax.swing.JButton();
        btn7_4 = new javax.swing.JButton();
        btn6_5 = new javax.swing.JButton();
        btn7_5 = new javax.swing.JButton();
        btn7_6 = new javax.swing.JButton();
        btn6_6 = new javax.swing.JButton();
        btn6_7 = new javax.swing.JButton();
        btn7_7 = new javax.swing.JButton();
        btn_iniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        btn0_0.setBackground(new java.awt.Color(153, 255, 204));
        btn0_0.setText("0");
        btn0_0.setPreferredSize(new java.awt.Dimension(50, 50));

        btn0_2.setBackground(new java.awt.Color(153, 255, 204));
        btn0_2.setText("2");
        btn0_2.setPreferredSize(new java.awt.Dimension(50, 50));

        btn0_1.setBackground(new java.awt.Color(153, 255, 204));
        btn0_1.setText("1");
        btn0_1.setPreferredSize(new java.awt.Dimension(50, 50));

        btn0_3.setBackground(new java.awt.Color(153, 255, 204));
        btn0_3.setText("3");
        btn0_3.setPreferredSize(new java.awt.Dimension(50, 50));

        btn0_7.setBackground(new java.awt.Color(153, 255, 204));
        btn0_7.setText("7");
        btn0_7.setPreferredSize(new java.awt.Dimension(50, 50));

        btn0_4.setBackground(new java.awt.Color(153, 255, 204));
        btn0_4.setText("4");
        btn0_4.setPreferredSize(new java.awt.Dimension(50, 50));

        btn0_5.setBackground(new java.awt.Color(153, 255, 204));
        btn0_5.setText("5");
        btn0_5.setPreferredSize(new java.awt.Dimension(50, 50));

        btn0_6.setBackground(new java.awt.Color(153, 255, 204));
        btn0_6.setText("6");
        btn0_6.setPreferredSize(new java.awt.Dimension(50, 50));

        btn1_0.setBackground(new java.awt.Color(153, 255, 204));
        btn1_0.setText("0");
        btn1_0.setPreferredSize(new java.awt.Dimension(50, 50));

        btn1_1.setBackground(new java.awt.Color(153, 255, 204));
        btn1_1.setText("1");
        btn1_1.setPreferredSize(new java.awt.Dimension(50, 50));

        btn1_2.setBackground(new java.awt.Color(153, 255, 204));
        btn1_2.setText("2");
        btn1_2.setPreferredSize(new java.awt.Dimension(50, 50));

        btn1_3.setBackground(new java.awt.Color(153, 255, 204));
        btn1_3.setText("3");
        btn1_3.setPreferredSize(new java.awt.Dimension(50, 50));

        btn1_4.setBackground(new java.awt.Color(153, 255, 204));
        btn1_4.setText("4");
        btn1_4.setPreferredSize(new java.awt.Dimension(50, 50));

        btn1_5.setBackground(new java.awt.Color(153, 255, 204));
        btn1_5.setText("5");
        btn1_5.setPreferredSize(new java.awt.Dimension(50, 50));

        btn1_6.setBackground(new java.awt.Color(153, 255, 204));
        btn1_6.setText("6");
        btn1_6.setPreferredSize(new java.awt.Dimension(50, 50));

        btn1_7.setBackground(new java.awt.Color(153, 255, 204));
        btn1_7.setText("7");
        btn1_7.setPreferredSize(new java.awt.Dimension(50, 50));

        btn2_0.setBackground(new java.awt.Color(153, 255, 204));
        btn2_0.setText("0");
        btn2_0.setPreferredSize(new java.awt.Dimension(50, 50));

        btn2_7.setBackground(new java.awt.Color(153, 255, 204));
        btn2_7.setText("7");
        btn2_7.setPreferredSize(new java.awt.Dimension(50, 50));

        btn2_1.setBackground(new java.awt.Color(153, 255, 204));
        btn2_1.setText("1");
        btn2_1.setPreferredSize(new java.awt.Dimension(50, 50));

        btn2_2.setBackground(new java.awt.Color(153, 255, 204));
        btn2_2.setText("2");
        btn2_2.setPreferredSize(new java.awt.Dimension(50, 50));

        btn2_3.setBackground(new java.awt.Color(153, 255, 204));
        btn2_3.setText("3");
        btn2_3.setPreferredSize(new java.awt.Dimension(50, 50));

        btn2_4.setBackground(new java.awt.Color(153, 255, 204));
        btn2_4.setText("4");
        btn2_4.setPreferredSize(new java.awt.Dimension(50, 50));

        btn2_5.setBackground(new java.awt.Color(153, 255, 204));
        btn2_5.setText("5");
        btn2_5.setPreferredSize(new java.awt.Dimension(50, 50));

        btn2_6.setBackground(new java.awt.Color(153, 255, 204));
        btn2_6.setText("6");
        btn2_6.setPreferredSize(new java.awt.Dimension(50, 50));

        btn3_0.setBackground(new java.awt.Color(153, 255, 204));
        btn3_0.setText("0");
        btn3_0.setPreferredSize(new java.awt.Dimension(50, 50));

        btn3_1.setBackground(new java.awt.Color(153, 255, 204));
        btn3_1.setText("1");
        btn3_1.setPreferredSize(new java.awt.Dimension(50, 50));

        btn3_2.setBackground(new java.awt.Color(153, 255, 204));
        btn3_2.setText("2");
        btn3_2.setPreferredSize(new java.awt.Dimension(50, 50));

        btn3_3.setBackground(new java.awt.Color(153, 255, 204));
        btn3_3.setText("3");
        btn3_3.setPreferredSize(new java.awt.Dimension(50, 50));

        btn3_4.setBackground(new java.awt.Color(153, 255, 204));
        btn3_4.setText("4");
        btn3_4.setPreferredSize(new java.awt.Dimension(50, 50));

        btn3_5.setBackground(new java.awt.Color(153, 255, 204));
        btn3_5.setText("5");
        btn3_5.setPreferredSize(new java.awt.Dimension(50, 50));

        btn3_6.setBackground(new java.awt.Color(153, 255, 204));
        btn3_6.setText("6");
        btn3_6.setPreferredSize(new java.awt.Dimension(50, 50));

        btn3_7.setBackground(new java.awt.Color(153, 255, 204));
        btn3_7.setText("7");
        btn3_7.setPreferredSize(new java.awt.Dimension(50, 50));

        btn4_7.setBackground(new java.awt.Color(153, 255, 204));
        btn4_7.setText("7");
        btn4_7.setPreferredSize(new java.awt.Dimension(50, 50));

        btn4_6.setBackground(new java.awt.Color(153, 255, 204));
        btn4_6.setText("6");
        btn4_6.setPreferredSize(new java.awt.Dimension(50, 50));

        btn4_5.setBackground(new java.awt.Color(153, 255, 204));
        btn4_5.setText("5");
        btn4_5.setPreferredSize(new java.awt.Dimension(50, 50));

        btn4_4.setBackground(new java.awt.Color(153, 255, 204));
        btn4_4.setText("4");
        btn4_4.setPreferredSize(new java.awt.Dimension(50, 50));

        btn4_3.setBackground(new java.awt.Color(153, 255, 204));
        btn4_3.setText("3");
        btn4_3.setPreferredSize(new java.awt.Dimension(50, 50));

        btn4_2.setBackground(new java.awt.Color(153, 255, 204));
        btn4_2.setText("2");
        btn4_2.setPreferredSize(new java.awt.Dimension(50, 50));

        btn4_1.setBackground(new java.awt.Color(153, 255, 204));
        btn4_1.setText("1");
        btn4_1.setPreferredSize(new java.awt.Dimension(50, 50));

        btn4_0.setBackground(new java.awt.Color(153, 255, 204));
        btn4_0.setText("0");
        btn4_0.setPreferredSize(new java.awt.Dimension(50, 50));

        btn5_0.setBackground(new java.awt.Color(153, 255, 204));
        btn5_0.setText("0");
        btn5_0.setPreferredSize(new java.awt.Dimension(50, 50));

        btn5_1.setBackground(new java.awt.Color(153, 255, 204));
        btn5_1.setText("1");
        btn5_1.setPreferredSize(new java.awt.Dimension(50, 50));

        btn5_2.setBackground(new java.awt.Color(153, 255, 204));
        btn5_2.setText("2");
        btn5_2.setPreferredSize(new java.awt.Dimension(50, 50));

        btn5_3.setBackground(new java.awt.Color(153, 255, 204));
        btn5_3.setText("3");
        btn5_3.setPreferredSize(new java.awt.Dimension(50, 50));

        btn5_4.setBackground(new java.awt.Color(153, 255, 204));
        btn5_4.setText("4");
        btn5_4.setPreferredSize(new java.awt.Dimension(50, 50));

        btn5_5.setBackground(new java.awt.Color(153, 255, 204));
        btn5_5.setText("5");
        btn5_5.setPreferredSize(new java.awt.Dimension(50, 50));

        btn5_6.setBackground(new java.awt.Color(153, 255, 204));
        btn5_6.setText("6");
        btn5_6.setPreferredSize(new java.awt.Dimension(50, 50));

        btn5_7.setBackground(new java.awt.Color(153, 255, 204));
        btn5_7.setText("7");
        btn5_7.setPreferredSize(new java.awt.Dimension(50, 50));

        btn7_0.setBackground(new java.awt.Color(153, 255, 204));
        btn7_0.setText("0");
        btn7_0.setPreferredSize(new java.awt.Dimension(50, 50));

        btn6_0.setBackground(new java.awt.Color(153, 255, 204));
        btn6_0.setText("0");
        btn6_0.setPreferredSize(new java.awt.Dimension(50, 50));

        btn6_1.setBackground(new java.awt.Color(153, 255, 204));
        btn6_1.setText("1");
        btn6_1.setPreferredSize(new java.awt.Dimension(50, 50));

        btn7_1.setBackground(new java.awt.Color(153, 255, 204));
        btn7_1.setText("1");
        btn7_1.setPreferredSize(new java.awt.Dimension(50, 50));

        btn6_2.setBackground(new java.awt.Color(153, 255, 204));
        btn6_2.setText("2");
        btn6_2.setPreferredSize(new java.awt.Dimension(50, 50));

        btn7_2.setBackground(new java.awt.Color(153, 255, 204));
        btn7_2.setText("2");
        btn7_2.setPreferredSize(new java.awt.Dimension(50, 50));

        btn6_3.setBackground(new java.awt.Color(153, 255, 204));
        btn6_3.setText("3");
        btn6_3.setPreferredSize(new java.awt.Dimension(50, 50));

        btn7_3.setBackground(new java.awt.Color(153, 255, 204));
        btn7_3.setText("3");
        btn7_3.setPreferredSize(new java.awt.Dimension(50, 50));

        btn6_4.setBackground(new java.awt.Color(153, 255, 204));
        btn6_4.setText("4");
        btn6_4.setPreferredSize(new java.awt.Dimension(50, 50));

        btn7_4.setBackground(new java.awt.Color(153, 255, 204));
        btn7_4.setText("4");
        btn7_4.setPreferredSize(new java.awt.Dimension(50, 50));

        btn6_5.setBackground(new java.awt.Color(153, 255, 204));
        btn6_5.setText("5");
        btn6_5.setPreferredSize(new java.awt.Dimension(50, 50));

        btn7_5.setBackground(new java.awt.Color(153, 255, 204));
        btn7_5.setText("5");
        btn7_5.setPreferredSize(new java.awt.Dimension(50, 50));

        btn7_6.setBackground(new java.awt.Color(153, 255, 204));
        btn7_6.setText("6");
        btn7_6.setPreferredSize(new java.awt.Dimension(50, 50));

        btn6_6.setBackground(new java.awt.Color(153, 255, 204));
        btn6_6.setText("6");
        btn6_6.setPreferredSize(new java.awt.Dimension(50, 50));

        btn6_7.setBackground(new java.awt.Color(153, 255, 204));
        btn6_7.setText("7");
        btn6_7.setPreferredSize(new java.awt.Dimension(50, 50));

        btn7_7.setBackground(new java.awt.Color(153, 255, 204));
        btn7_7.setText("7");
        btn7_7.setPreferredSize(new java.awt.Dimension(50, 50));

        btn_iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/iniciar.png"))); // NOI18N
        btn_iniciar.setText("INICIAR");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn5_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn5_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn5_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn5_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn5_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn5_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn5_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn5_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn4_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn4_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn4_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn4_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn4_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn4_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn4_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn4_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn3_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn3_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn3_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn3_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn3_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn2_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn2_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn2_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn2_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn2_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn1_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn1_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn1_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn1_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn0_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn0_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn0_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn0_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn0_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn0_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn0_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn0_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn6_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn6_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn6_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn6_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn6_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn6_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn6_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn6_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn7_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn7_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn7_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn7_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn7_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn7_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn7_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn7_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn6_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_iniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        // TODO add your handling code here:
        this.limpiarTablero();
        Genetica reinas = new Genetica();
        Cromosoma c = reinas.algoritmoGenetico();
        for (int i = 0; i < c.vec_solucion.length; i++) {
            colocarIcono(c.vec_solucion[i],i);
        }


    }//GEN-LAST:event_btn_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0_0;
    private javax.swing.JButton btn0_1;
    private javax.swing.JButton btn0_2;
    private javax.swing.JButton btn0_3;
    private javax.swing.JButton btn0_4;
    private javax.swing.JButton btn0_5;
    private javax.swing.JButton btn0_6;
    private javax.swing.JButton btn0_7;
    private javax.swing.JButton btn1_0;
    private javax.swing.JButton btn1_1;
    private javax.swing.JButton btn1_2;
    private javax.swing.JButton btn1_3;
    private javax.swing.JButton btn1_4;
    private javax.swing.JButton btn1_5;
    private javax.swing.JButton btn1_6;
    private javax.swing.JButton btn1_7;
    private javax.swing.JButton btn2_0;
    private javax.swing.JButton btn2_1;
    private javax.swing.JButton btn2_2;
    private javax.swing.JButton btn2_3;
    private javax.swing.JButton btn2_4;
    private javax.swing.JButton btn2_5;
    private javax.swing.JButton btn2_6;
    private javax.swing.JButton btn2_7;
    private javax.swing.JButton btn3_0;
    private javax.swing.JButton btn3_1;
    private javax.swing.JButton btn3_2;
    private javax.swing.JButton btn3_3;
    private javax.swing.JButton btn3_4;
    private javax.swing.JButton btn3_5;
    private javax.swing.JButton btn3_6;
    private javax.swing.JButton btn3_7;
    private javax.swing.JButton btn4_0;
    private javax.swing.JButton btn4_1;
    private javax.swing.JButton btn4_2;
    private javax.swing.JButton btn4_3;
    private javax.swing.JButton btn4_4;
    private javax.swing.JButton btn4_5;
    private javax.swing.JButton btn4_6;
    private javax.swing.JButton btn4_7;
    private javax.swing.JButton btn5_0;
    private javax.swing.JButton btn5_1;
    private javax.swing.JButton btn5_2;
    private javax.swing.JButton btn5_3;
    private javax.swing.JButton btn5_4;
    private javax.swing.JButton btn5_5;
    private javax.swing.JButton btn5_6;
    private javax.swing.JButton btn5_7;
    private javax.swing.JButton btn6_0;
    private javax.swing.JButton btn6_1;
    private javax.swing.JButton btn6_2;
    private javax.swing.JButton btn6_3;
    private javax.swing.JButton btn6_4;
    private javax.swing.JButton btn6_5;
    private javax.swing.JButton btn6_6;
    private javax.swing.JButton btn6_7;
    private javax.swing.JButton btn7_0;
    private javax.swing.JButton btn7_1;
    private javax.swing.JButton btn7_2;
    private javax.swing.JButton btn7_3;
    private javax.swing.JButton btn7_4;
    private javax.swing.JButton btn7_5;
    private javax.swing.JButton btn7_6;
    private javax.swing.JButton btn7_7;
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void limpiarTablero() {
        btn0_0.setText("");
        btn0_1.setText("");
        btn0_2.setText("");
        btn0_3.setText("");
        btn0_4.setText("");
        btn0_5.setText("");
        btn0_6.setText("");
        btn0_7.setText("");
        btn1_0.setText("");
        btn1_1.setText("");
        btn1_2.setText("");
        btn1_3.setText("");
        btn1_4.setText("");
        btn1_5.setText("");
        btn1_6.setText("");
        btn1_7.setText("");
        btn2_0.setText("");
        btn2_1.setText("");
        btn2_2.setText("");
        btn2_3.setText("");
        btn2_4.setText("");
        btn2_5.setText("");
        btn2_6.setText("");
        btn2_7.setText("");
        btn3_0.setText("");
        btn3_1.setText("");
        btn3_2.setText("");
        btn3_3.setText("");
        btn3_4.setText("");
        btn3_5.setText("");
        btn3_6.setText("");
        btn3_7.setText("");
        btn4_0.setText("");
        btn4_1.setText("");
        btn4_2.setText("");
        btn4_3.setText("");
        btn4_4.setText("");
        btn4_5.setText("");
        btn4_6.setText("");
        btn4_7.setText("");
        btn5_0.setText("");
        btn5_1.setText("");
        btn5_2.setText("");
        btn5_3.setText("");
        btn5_4.setText("");
        btn5_5.setText("");
        btn5_6.setText("");
        btn5_7.setText("");
        btn6_0.setText("");
        btn6_1.setText("");
        btn6_2.setText("");
        btn6_3.setText("");
        btn6_4.setText("");
        btn6_5.setText("");
        btn6_6.setText("");
        btn6_7.setText("");
        btn7_0.setText("");
        btn7_1.setText("");
        btn7_2.setText("");
        btn7_3.setText("");
        btn7_4.setText("");
        btn7_5.setText("");
        btn7_6.setText("");
        btn7_7.setText("");
        
         btn0_0.setIcon(null);
        btn0_1.setIcon(null);
        btn0_2.setIcon(null);
        btn0_3.setIcon(null);
        btn0_4.setIcon(null);
        btn0_5.setIcon(null);
        btn0_6.setIcon(null);
        btn0_7.setIcon(null);
        btn1_0.setIcon(null);
        btn1_1.setIcon(null);
        btn1_2.setIcon(null);
        btn1_3.setIcon(null);
        btn1_4.setIcon(null);
        btn1_5.setIcon(null);
        btn1_6.setIcon(null);
        btn1_7.setIcon(null);
        btn2_0.setIcon(null);
        btn2_1.setIcon(null);
        btn2_2.setIcon(null);
        btn2_3.setIcon(null);
        btn2_4.setIcon(null);
        btn2_5.setIcon(null);
        btn2_6.setIcon(null);
        btn2_7.setIcon(null);
        btn3_0.setIcon(null);
        btn3_1.setIcon(null);
        btn3_2.setIcon(null);
        btn3_3.setIcon(null);
        btn3_4.setIcon(null);
        btn3_5.setIcon(null);
        btn3_6.setIcon(null);
        btn3_7.setIcon(null);
        btn4_0.setIcon(null);
        btn4_1.setIcon(null);
        btn4_2.setIcon(null);
        btn4_3.setIcon(null);
        btn4_4.setIcon(null);
        btn4_5.setIcon(null);
        btn4_6.setIcon(null);
        btn4_7.setIcon(null);
        btn5_0.setIcon(null);
        btn5_1.setIcon(null);
        btn5_2.setIcon(null);
        btn5_3.setIcon(null);
        btn5_4.setIcon(null);
        btn5_5.setIcon(null);
        btn5_6.setIcon(null);
        btn5_7.setIcon(null);
        btn6_0.setIcon(null);
        btn6_1.setIcon(null);
        btn6_2.setIcon(null);
        btn6_3.setIcon(null);
        btn6_4.setIcon(null);
        btn6_5.setIcon(null);
        btn6_6.setIcon(null);
        btn6_7.setIcon(null);
        btn7_0.setIcon(null);
        btn7_1.setIcon(null);
        btn7_2.setIcon(null);
        btn7_3.setIcon(null);
        btn7_4.setIcon(null);
        btn7_5.setIcon(null);
        btn7_6.setIcon(null);
        btn7_7.setIcon(null);
    }

    private void colocarIcono(int f, int c) {
        switch (f) {
            case 0:
                switch (c) {
                    case 0:
                        this.btn0_0.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 1:
                        this.btn1_0.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 2:
                        this.btn2_0.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 3:
                        this.btn3_0.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 4:
                        this.btn4_0.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 5:
                        this.btn5_0.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 6:
                        this.btn6_0.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 7:
                        this.btn7_0.setIcon(new ImageIcon("reina.png"));
                        break;
                }
                break;
            case 1:
                switch (c) {
                    case 0:
                        this.btn0_1.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 1:
                        this.btn1_1.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 2:
                        this.btn2_1.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 3:
                        this.btn3_1.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 4:
                        this.btn4_1.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 5:
                        this.btn5_1.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 6:
                        this.btn6_1.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 7:
                        this.btn7_1.setIcon(new ImageIcon("reina.png"));
                }
                break;
            case 2:
                switch (c) {
                     case 0:
                        this.btn0_2.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 1:
                        this.btn1_2.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 2:
                        this.btn2_2.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 3:
                        this.btn3_2.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 4:
                        this.btn4_2.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 5:
                        this.btn5_2.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 6:
                        this.btn6_2.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 7:
                        this.btn7_2.setIcon(new ImageIcon("reina.png"));
                }
                break;
            case 3:
                switch (c) {
                   case 0:
                        this.btn0_3.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 1:
                        this.btn1_3.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 2:
                        this.btn2_3.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 3:
                        this.btn3_3.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 4:
                        this.btn4_3.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 5:
                        this.btn5_3.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 6:
                        this.btn6_3.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 7:
                        this.btn7_3.setIcon(new ImageIcon("reina.png"));
                        break;
                }
                break;
            case 4:
                switch (c) {
                    case 0:
                        this.btn0_4.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 1:
                        this.btn1_4.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 2:
                        this.btn2_4.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 3:
                        this.btn3_4.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 4:
                        this.btn4_4.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 5:
                        this.btn5_4.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 6:
                        this.btn6_4.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 7:
                        this.btn7_4.setIcon(new ImageIcon("reina.png"));
                        break;
                }
                break;
            case 5:
                switch (c) {
                     case 0:
                        this.btn0_5.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 1:
                        this.btn1_5.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 2:
                        this.btn2_5.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 3:
                        this.btn3_5.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 4:
                        this.btn4_5.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 5:
                        this.btn5_5.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 6:
                        this.btn6_5.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 7:
                        this.btn7_5.setIcon(new ImageIcon("reina.png"));
                        break;                }
                break;

            case 6:
                switch (c) {
                    case 0:
                        this.btn0_6.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 1:
                        this.btn1_6.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 2:
                        this.btn2_6.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 3:
                        this.btn3_6.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 4:
                        this.btn4_6.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 5:
                        this.btn5_6.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 6:
                        this.btn6_6.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 7:
                        this.btn7_6.setIcon(new ImageIcon("reina.png"));
                        break;
                }
                break;
                
            case 7:
                switch(c){
                     case 0:
                        this.btn0_7.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 1:
                        this.btn1_7.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 2:
                        this.btn2_7.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 3:
                        this.btn3_7.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 4:
                        this.btn4_7.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 5:
                        this.btn5_7.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 6:
                        this.btn6_7.setIcon(new ImageIcon("reina.png"));
                        break;
                    case 7:
                        this.btn7_7.setIcon(new ImageIcon("reina.png"));
                        break;
                }
                break;

        }
    }
}
